apiVersion: apps/v1
kind: Deployment
metadata:
  name: user1-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user1-desktop
  template:
    metadata:
      labels:
        app: user1-desktop
    spec:
      containers:
        - name: desktop
          image: dorowu/ubuntu-desktop-lxde-vnc
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user1-desktop-svc
spec:
  type: NodePort
  selector:
    app: user1-desktop
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
